### ISSUE TITLE
Prompt outputs failed validation PulidFluxModelLoader: - Value not in list: pulid_file: 'pulid_flux_v0.9.0.safetensors' not in []

### ISSUE THREAD

**Issue by adamreading** [balazik/ComfyUI-PuLID-Flux#1]
Hi - Thanks for making this - I spent 3 failed days on the storydiffusion version lol

Day 1 here...

My cloud instance works like data/app/models/pulid - and the file is in there - but I can't point your loader at it and it can't see it...

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/581aa21e-f9be-4bd4-8430-85fa05934660">

**Comment by balazik** [comment]
@adamreading Hi, thanx for trying the PulLID-Flux node. 

You can try to configure with `extra_model_paths.yaml.example`. 
- find the `extra_model_paths.yaml.example` file in comfy install directory and rename it to `extra_model_paths.yaml`
- then edit with any text editor like this (comment out the whole a111 root...): 
```
#Rename this to extra_model_paths.yaml and ComfyUI will load it

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
#a111:
#    base_path: D:\Sources\Python\Gerulata\ml\stable-diffusion-ui\stable-diffusion-webui\
#
#    checkpoints: models/Stable-diffusion
#    configs: models/Stable-diffusion
#    vae: models/VAE
#    loras: |
#         models/Lora
#         models/LyCORIS
#    upscale_models: |
#                  models/ESRGAN
#                  models/RealESRGAN
#                  models/SwinIR
#    embeddings: embeddings
#    hypernetworks: models/hypernetworks
#    controlnet: models/ControlNet
#    ipadapter: models/ControlNet
#    instantid: models/ControlNet
#    pulid: models/pulid

#config for comfyui
#your base path should be either an existing comfy install or a central folder where you store all of your models, loras, etc.

comfyui:
     base_path: path/to/comfyui/ #<------ here goes the path to your comfy root dir
     pulid: models/pulid         #<------ add this line
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/

#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes

```
This should redirect comfy/nodes to your models. If not, and you have this file already configured, please paste it here. I will look at it.
